import { Mission, TuningState, ModNode, Rival, SkillNode } from './types';

// Base Car Stats (Stock Hatchback)
export const INITIAL_MONEY = 1000;
export const BASE_TUNING: TuningState = {
	maxTorque: 180,
	torqueCurve: [
		{ rpm: 0, factor: 0.3 },
		{ rpm: 2000, factor: 0.6 },
		{ rpm: 4000, factor: 0.9 },
		{ rpm: 5500, factor: 1.0 },
		{ rpm: 6500, factor: 0.85 },
	],
	redlineRPM: 6500,
	idleRPM: 800,
	flywheelMass: 0.8, // Heavy stock flywheel
	compressionRatio: 9.0,

	cylinders: 4,
	exhaustOpenness: 0.1,
	backfireAggression: 0.0,
	turboIntensity: 0.0,

	finalDriveRatio: 4.1,
	gearRatios: {
		0: 0,
		1: 3.5,
		2: 2.1,
		3: 1.4,
		4: 1.0,
		5: 0.8,
		6: 0.7,
	},

	mass: 1400,
	dragCoefficient: 0.35,
	tireGrip: 1.0,
	brakingForce: 3000, // New default braking force
	color: '#3b82f6', // Blue
};

// --- THE MOD TREE ---
export const MOD_TREE: ModNode[] = [
	// ===== ROOT NODES =====
	{
		id: 'ecu1',
		name: 'Sport ECU',
		description: 'Basic tune. +20Nm',
		cost: 200,
		type: 'ENGINE',
		parentId: null,
		conflictsWith: [],
		x: 0,
		y: 0,
		stats: { maxTorque: 20, redlineRPM: 6800 },
		tuningOptions: [
			{
				id: 'rev_limiter',
				name: 'Rev Limiter',
				min: 5000,
				max: 15000,
				step: 100,
				defaultValue: 6800,
				unit: 'RPM',
				statAffected: 'redlineRPM',
			},
			{
				id: 'idle_rpm',
				name: 'Idle RPM',
				min: 800,
				max: 1500,
				step: 50,
				defaultValue: 1000,
				unit: 'RPM',
				statAffected: 'idleRPM',
			},
		],
	},
	{
		id: 'muffler_sport',
		name: 'Sport Muffler',
		description: 'Better flow, deeper tone.',
		cost: 300,
		type: 'ENGINE',
		parentId: null,
		conflictsWith: ['muffler_race', 'muffler_straight'],
		x: -1,
		y: 1,
		stats: { exhaustOpenness: 0.3 },
		soundProfile: 'sport',
	},
	{
		id: 'muffler_race',
		name: 'Race Muffler',
		description: 'Loud and aggressive.',
		cost: 600,
		type: 'ENGINE',
		parentId: null,
		conflictsWith: ['muffler_sport', 'muffler_straight'],
		x: -1,
		y: 2,
		stats: { exhaustOpenness: 0.6 },
		soundProfile: 'race',
	},
	{
		id: 'muffler_straight',
		name: 'Straight Pipe',
		description: 'Ear bleeding loud.',
		cost: 1000,
		type: 'ENGINE',
		parentId: null,
		conflictsWith: ['muffler_sport', 'muffler_race'],
		x: -1,
		y: 3,
		stats: { exhaustOpenness: 1.0 },
		soundProfile: 'straight_pipe',
	},
	{
		id: 'tires1',
		name: 'Sport Tires',
		description: 'Better compound. +0.2 Grip',
		cost: 400,
		type: 'TIRES',
		parentId: null,
		conflictsWith: [],
		x: 0,
		y: 3,
		stats: { tireGrip: 1.2 },
		tuningOptions: [
			{
				id: 'tire_pressure',
				name: 'Tire Pressure',
				min: 20,
				max: 40,
				step: 1,
				defaultValue: 30,
				unit: 'PSI',
			},
		],
	},
	{
		id: 'weight1',
		name: 'Rear Seat Delete',
		description: '-50kg',
		cost: 150,
		type: 'WEIGHT',
		parentId: null,
		conflictsWith: [],
		x: 0,
		y: 5,
		stats: { mass: -50 },
	},
	{
		id: 'trans_root',
		name: 'Lightweight Flywheel',
		description: 'Faster revs',
		cost: 300,
		type: 'TRANSMISSION',
		parentId: null,
		conflictsWith: [],
		x: 0,
		y: -2,
		stats: { flywheelMass: 0.6 },
	},

	// ===== ENGINE BRANCH =====
	{
		id: 'intake',
		name: 'Cold Air Intake',
		description: 'Breaths better.',
		cost: 500,
		type: 'ENGINE',
		parentId: 'ecu1',
		conflictsWith: [],
		x: 1,
		y: 0,
		stats: { maxTorque: 15, exhaustOpenness: 0.3 },
	},

	// FORCED INDUCTION SPLIT: TURBO vs SUPERCHARGER vs NA
	{
		id: 'turbo_kit',
		name: 'Turbo Kit',
		description: 'Boost power! Adds lag.',
		cost: 2000,
		type: 'TURBO',
		parentId: 'intake',
		conflictsWith: ['na_cams', 'supercharger'],
		x: 2,
		y: -1,
		stats: {
			maxTorque: 120,
			turboIntensity: 0.6,
			exhaustOpenness: 0.5,
			torqueCurve: [
				{ rpm: 0, factor: 0.2 },
				{ rpm: 3000, factor: 0.5 },
				{ rpm: 4500, factor: 1.0 },
				{ rpm: 6800, factor: 0.9 },
			],
		},
		tuningOptions: [
			{
				id: 'boost_pressure',
				name: 'Boost Pressure',
				min: 0.3,
				max: 1.2,
				step: 0.1,
				defaultValue: 0.6,
				unit: 'BAR',
			},
		],
	},
	{
		id: 'supercharger',
		name: 'Roots Supercharger',
		description: 'Instant power, no lag!',
		cost: 2200,
		type: 'TURBO',
		parentId: 'intake',
		conflictsWith: ['turbo_kit', 'na_cams'],
		x: 2,
		y: 0.5,
		stats: {
			maxTorque: 100,
			exhaustOpenness: 0.4,
			torqueCurve: [
				{ rpm: 0, factor: 0.7 },
				{ rpm: 2000, factor: 0.9 },
				{ rpm: 4000, factor: 1.0 },
				{ rpm: 6500, factor: 0.85 },
			],
		},
	},
	{
		id: 'na_cams',
		name: 'Race Cams',
		description: 'High RPM power. Choppy idle.',
		cost: 1800,
		type: 'ENGINE',
		parentId: 'intake',
		conflictsWith: ['turbo_kit', 'supercharger'],
		x: 2,
		y: 2,
		stats: {
			maxTorque: 45,
			redlineRPM: 8500,
			idleRPM: 1200,
			exhaustOpenness: 0.6,
			flywheelMass: 0.4,
			torqueCurve: [
				{ rpm: 0, factor: 0.1 },
				{ rpm: 4000, factor: 0.6 },
				{ rpm: 6000, factor: 0.9 },
				{ rpm: 8500, factor: 1.0 },
			],
		},
	},

	// TURBO PATH
	{
		id: 'big_turbo',
		name: 'Big Turbo',
		description: 'Massive lag, massive power.',
		cost: 4500,
		type: 'TURBO',
		parentId: 'turbo_kit',
		conflictsWith: [],
		x: 3,
		y: -1.5,
		stats: {
			maxTorque: 180,
			turboIntensity: 1.0,
			exhaustOpenness: 0.8,
			backfireAggression: 0.8,
			torqueCurve: [
				{ rpm: 0, factor: 0.1 },
				{ rpm: 4000, factor: 0.3 },
				{ rpm: 5500, factor: 1.0 },
				{ rpm: 7500, factor: 1.0 },
			],
		},
		tuningOptions: [
			{
				id: 'boost_pressure',
				name: 'Boost Pressure',
				min: 0.8,
				max: 2.5,
				step: 0.1,
				defaultValue: 1.5,
				unit: 'BAR',
			},
		],
	},
	{
		id: 'antilag',
		name: 'Anti-Lag System',
		description: 'Eliminates turbo lag!',
		cost: 3000,
		type: 'TURBO',
		parentId: 'turbo_kit',
		conflictsWith: [],
		x: 3,
		y: -0.5,
		stats: {
			backfireAggression: 1.0,
			torqueCurve: [
				{ rpm: 0, factor: 0.5 },
				{ rpm: 2500, factor: 0.8 },
				{ rpm: 4500, factor: 1.0 },
				{ rpm: 6800, factor: 0.9 },
			],
		},
	},
	{
		id: 'wastegate',
		name: 'External Wastegate',
		description: 'Better boost control',
		cost: 1500,
		type: 'TURBO',
		parentId: 'big_turbo',
		conflictsWith: [],
		x: 4,
		y: -1.5,
		stats: { maxTorque: 30 },
	},
	{
		id: 'ball_bearing',
		name: 'Ball-Bearing Turbo',
		description: 'Faster spool',
		cost: 2000,
		type: 'TURBO',
		parentId: 'big_turbo',
		conflictsWith: [],
		x: 4,
		y: -0.8,
		stats: { turboIntensity: 0.9 },
		soundProfile: 'turbo_flutter',
	},

	// SUPERCHARGER PATH
	{
		id: 'twin_screw',
		name: 'Twin-Screw Blower',
		description: 'More efficient',
		cost: 4000,
		type: 'TURBO',
		parentId: 'supercharger',
		conflictsWith: [],
		x: 3,
		y: 0.5,
		stats: { maxTorque: 150, exhaustOpenness: 0.6 },
	},
	{
		id: 'centrifugal_sc',
		name: 'Centrifugal Supercharger',
		description: 'High-RPM power',
		cost: 3500,
		type: 'TURBO',
		parentId: 'supercharger',
		conflictsWith: [],
		x: 3,
		y: 1.2,
		stats: {
			maxTorque: 130,
			torqueCurve: [
				{ rpm: 0, factor: 0.4 },
				{ rpm: 3000, factor: 0.7 },
				{ rpm: 5500, factor: 1.0 },
				{ rpm: 7500, factor: 0.95 },
			],
		},
	},
	{
		id: 'sc_pulley',
		name: 'Overdrive Pulley',
		description: 'More boost!',
		cost: 1800,
		type: 'TURBO',
		parentId: 'twin_screw',
		conflictsWith: [],
		x: 4,
		y: 0.5,
		stats: { maxTorque: 60 },
	},

	// NA PATH
	{
		id: 'itb',
		name: 'Indiv. Throttle Bodies',
		description: 'Instant response.',
		cost: 4000,
		type: 'ENGINE',
		parentId: 'na_cams',
		conflictsWith: [],
		x: 3,
		y: 2,
		stats: {
			maxTorque: 50,
			redlineRPM: 9500,
			exhaustOpenness: 1.0,
			flywheelMass: 0.2,
			backfireAggression: 0.5,
		},
	},
	{
		id: 'ported_heads',
		name: 'Ported Heads',
		description: 'Better flow',
		cost: 2500,
		type: 'ENGINE',
		parentId: 'na_cams',
		conflictsWith: [],
		x: 3,
		y: 2.7,
		stats: { maxTorque: 35 },
	},
	{
		id: 'stroker',
		name: 'Stroker Kit',
		description: '+0.4L displacement',
		cost: 5000,
		type: 'ENGINE',
		parentId: 'ported_heads',
		conflictsWith: [],
		x: 4,
		y: 2.7,
		stats: { maxTorque: 70, redlineRPM: 8800 },
	},
	{
		id: 'titanium_valves',
		name: 'Titanium Valves',
		description: 'Lighter, higher RPM',
		cost: 3500,
		type: 'ENGINE',
		parentId: 'itb',
		conflictsWith: [],
		x: 4,
		y: 2,
		stats: { redlineRPM: 10000 },
	},

	// ===== TRANSMISSION BRANCH =====
	{
		id: 'close_ratio',
		name: 'Close-Ratio Gearbox',
		description: 'Better acceleration',
		cost: 2000,
		type: 'TRANSMISSION',
		parentId: 'trans_root',
		conflictsWith: ['sequential'],
		x: 1,
		y: -2,
		stats: {
			gearRatios: {
				0: 0,
				1: 3.8,
				2: 2.4,
				3: 1.6,
				4: 1.15,
				5: 0.9,
				6: 0.75,
			},
		},
	},
	{
		id: 'sequential',
		name: 'Sequential Gearbox',
		description: 'Lightning shifts',
		cost: 4500,
		type: 'TRANSMISSION',
		parentId: 'trans_root',
		conflictsWith: ['close_ratio'],
		x: 1,
		y: -1.3,
		stats: {
			flywheelMass: 0.3,
			gearRatios: {
				0: 0,
				1: 3.6,
				2: 2.3,
				3: 1.5,
				4: 1.1,
				5: 0.85,
				6: 0.7,
			},
		},
	},
	{
		id: 'carbon_clutch',
		name: 'Carbon Clutch',
		description: 'Better power transfer',
		cost: 1200,
		type: 'TRANSMISSION',
		parentId: 'trans_root',
		conflictsWith: [],
		x: 1,
		y: -2.7,
		stats: { flywheelMass: 0.4 },
	},
	{
		id: 'lsd',
		name: 'Limited Slip Diff',
		description: 'Better traction',
		cost: 1800,
		type: 'TRANSMISSION',
		parentId: 'close_ratio',
		conflictsWith: [],
		x: 2,
		y: -2,
		stats: { tireGrip: 1.3 },
	},

	// ===== WEIGHT BRANCH =====
	{
		id: 'weight2',
		name: 'Carbon Hood',
		description: '-100kg',
		cost: 1200,
		type: 'WEIGHT',
		parentId: 'weight1',
		conflictsWith: [],
		x: 1,
		y: 5,
		stats: { mass: -100 },
	},
	{
		id: 'weight3',
		name: 'Stripped Interior',
		description: '-250kg total',
		cost: 2500,
		type: 'WEIGHT',
		parentId: 'weight2',
		conflictsWith: [],
		x: 2,
		y: 5,
		stats: { mass: -250 },
	},
	{
		id: 'carbon_panels',
		name: 'Carbon Body Panels',
		description: '-350kg total',
		cost: 4000,
		type: 'WEIGHT',
		parentId: 'weight3',
		conflictsWith: [],
		x: 3,
		y: 5,
		stats: { mass: -350 },
	},

	// ===== TIRES BRANCH =====
	{
		id: 'tires2',
		name: 'Semi-Slicks',
		description: 'Track day tires.',
		cost: 1200,
		type: 'TIRES',
		parentId: 'tires1',
		conflictsWith: [],
		x: 1,
		y: 3,
		stats: { tireGrip: 1.6 },
	},
	{
		id: 'tires3',
		name: 'Drag Radials',
		description: 'Glue.',
		cost: 2500,
		type: 'TIRES',
		parentId: 'tires2',
		conflictsWith: ['drag_slicks'],
		x: 2,
		y: 3,
		stats: { tireGrip: 2.2 },
	},
	{
		id: 'drag_slicks',
		name: 'Full Drag Slicks',
		description: 'Ultimate grip',
		cost: 3500,
		type: 'TIRES',
		parentId: 'tires2',
		conflictsWith: ['tires3'],
		x: 2,
		y: 3.7,
		stats: { tireGrip: 2.8 },
	},

	// ===== NITROUS BRANCH =====
	{
		id: 'nitrous_50',
		name: '50-Shot Nitrous',
		description: '+50HP boost',
		cost: 1500,
		type: 'NITROUS',
		parentId: null,
		conflictsWith: [],
		x: 0,
		y: -4,
		stats: { maxTorque: 70 },
	},
	{
		id: 'nitrous_100',
		name: '100-Shot Nitrous',
		description: '+100HP boost',
		cost: 2500,
		type: 'NITROUS',
		parentId: 'nitrous_50',
		conflictsWith: [],
		x: 1,
		y: -4,
		stats: { maxTorque: 140 },
	},
	{
		id: 'nitrous_200',
		name: '200-Shot Nitrous',
		description: '+200HP! Risky!',
		cost: 5000,
		type: 'NITROUS',
		parentId: 'nitrous_100',
		conflictsWith: [],
		x: 2,
		y: -4,
		stats: { maxTorque: 280 },
	},
	{
		id: 'progressive_nos',
		name: 'Progressive Controller',
		description: 'Smoother delivery',
		cost: 1800,
		type: 'NITROUS',
		parentId: 'nitrous_100',
		conflictsWith: [],
		x: 2,
		y: -4.7,
		stats: {},
	},

	// ===== FUEL SYSTEM BRANCH =====
	{
		id: 'fuel_pump',
		name: 'High-Flow Fuel Pump',
		description: 'More fuel flow',
		cost: 800,
		type: 'FUEL',
		parentId: null,
		conflictsWith: [],
		x: 0,
		y: 6.5,
		stats: { maxTorque: 10 },
	},
	{
		id: 'injectors',
		name: '1000cc Injectors',
		description: 'High flow injectors',
		cost: 1500,
		type: 'FUEL',
		parentId: 'fuel_pump',
		conflictsWith: [],
		x: 1,
		y: 6.5,
		stats: { maxTorque: 20 },
	},
	{
		id: 'e85',
		name: 'E85 Conversion',
		description: 'More power potential',
		cost: 2000,
		type: 'FUEL',
		parentId: 'injectors',
		conflictsWith: [],
		x: 2,
		y: 6.5,
		stats: { maxTorque: 60 },
	},
	{
		id: 'fuel_rail',
		name: 'Adjustable Fuel Rail',
		description: 'Better fuel pressure',
		cost: 1200,
		type: 'FUEL',
		parentId: 'injectors',
		conflictsWith: [],
		x: 2,
		y: 7.2,
		stats: { maxTorque: 15 },
	},

	// ===== COOLING BRANCH =====
	{
		id: 'radiator',
		name: 'Performance Radiator',
		description: 'Better cooling',
		cost: 900,
		type: 'COOLING',
		parentId: null,
		conflictsWith: [],
		x: 0,
		y: -5.5,
		stats: { maxTorque: 5 },
	},
	{
		id: 'intercooler',
		name: 'Front-Mount Intercooler',
		description: 'Cooler intake temps',
		cost: 1800,
		type: 'COOLING',
		parentId: 'radiator',
		conflictsWith: [],
		x: 1,
		y: -5.5,
		stats: { maxTorque: 30 },
	},
	{
		id: 'oil_cooler',
		name: 'Oil Cooler',
		description: 'Keeps oil cool',
		cost: 1200,
		type: 'COOLING',
		parentId: 'radiator',
		conflictsWith: [],
		x: 1,
		y: -6.2,
		stats: { maxTorque: 5 },
	},
	{
		id: 'methanol',
		name: 'Methanol Injection',
		description: 'Chemical intercooler',
		cost: 2500,
		type: 'COOLING',
		parentId: 'intercooler',
		conflictsWith: [],
		x: 2,
		y: -5.5,
		stats: { maxTorque: 40 },
	},

	// ===== AERODYNAMICS BRANCH =====
	{
		id: 'spoiler',
		name: 'Rear Spoiler',
		description: 'Reduces drag',
		cost: 800,
		type: 'AERO',
		parentId: null,
		conflictsWith: [],
		x: 5,
		y: 0,
		stats: { dragCoefficient: 0.32 },
	},
	{
		id: 'splitter',
		name: 'Front Splitter',
		description: 'Better stability',
		cost: 1000,
		type: 'AERO',
		parentId: 'spoiler',
		conflictsWith: [],
		x: 6,
		y: 0,
		stats: { dragCoefficient: 0.3 },
	},
	{
		id: 'diffuser',
		name: 'Rear Diffuser',
		description: 'Improved airflow',
		cost: 1500,
		type: 'AERO',
		parentId: 'splitter',
		conflictsWith: [],
		x: 7,
		y: 0,
		stats: { dragCoefficient: 0.28 },
	},
	{
		id: 'underbody',
		name: 'Underbody Panels',
		description: 'Smooth airflow',
		cost: 2000,
		type: 'AERO',
		parentId: 'diffuser',
		conflictsWith: [],
		x: 8,
		y: 0,
		stats: { dragCoefficient: 0.25 },
	},

	// ===== SUSPENSION BRANCH =====
	{
		id: 'coilovers',
		name: 'Coilover Suspension',
		description: 'Better launch',
		cost: 1500,
		type: 'SUSPENSION',
		parentId: null,
		conflictsWith: [],
		x: 5,
		y: 2,
		stats: { tireGrip: 1.15 },
	},

	// ===== SPECIAL / RARE MODS =====
	// These are only visible if the car comes with them (Rare Junkyard Finds)

	// --- ROTARY ENGINE TREE ---
	{
		id: 'rotary_engine',
		name: '13B-REW Rotary',
		description: 'Legendary Rotary Power',
		cost: 10000,
		type: 'ENGINE',
		parentId: null,
		conflictsWith: ['vtec_engine', 'ecu1'], // Replaces standard engine/ecu
		x: 10,
		y: 0,
		stats: {
			maxTorque: 180, // Low torque
			redlineRPM: 9000,
			idleRPM: 1500,
			flywheelMass: 0.3,
			exhaustOpenness: 0.8,
			backfireAggression: 1.0,
			cylinders: 0, // Rotary
			torqueCurve: [
				{ rpm: 0, factor: 0.1 },
				{ rpm: 4000, factor: 0.4 },
				{ rpm: 7000, factor: 0.9 },
				{ rpm: 9000, factor: 1.0 },
			],
		},
		soundProfile: 'rotary',
		isSpecial: true,
	},
	{
		id: 'rotary_turbo',
		name: 'Twin Sequential Turbos',
		description: 'Boost for the Dorito',
		cost: 5000,
		type: 'TURBO',
		parentId: 'rotary_engine',
		conflictsWith: [],
		x: 11,
		y: 0,
		stats: {
			maxTorque: 150,
			turboIntensity: 0.8,
			torqueCurve: [
				{ rpm: 0, factor: 0.2 },
				{ rpm: 3000, factor: 0.6 },
				{ rpm: 5000, factor: 1.0 },
				{ rpm: 8000, factor: 0.9 },
			],
		},
		isSpecial: true,
	},
	{
		id: 'rotary_porting',
		name: 'Bridge Port',
		description: 'Brap brap brap',
		cost: 3000,
		type: 'ENGINE',
		parentId: 'rotary_engine',
		conflictsWith: [],
		x: 10,
		y: 1,
		stats: {
			redlineRPM: 10500,
			idleRPM: 2000,
			maxTorque: 40,
			exhaustOpenness: 1.0,
		},
		isSpecial: true,
	},

	// --- VTEC ENGINE TREE ---
	{
		id: 'vtec_engine',
		name: 'K20 Type-R',
		description: 'VTEC just kicked in!',
		cost: 12000,
		type: 'ENGINE',
		parentId: null,
		conflictsWith: ['rotary_engine', 'ecu1'],
		x: 10,
		y: 3,
		stats: {
			maxTorque: 200,
			redlineRPM: 8800,
			idleRPM: 900,
			cylinders: 4,
			torqueCurve: [
				{ rpm: 0, factor: 0.3 },
				{ rpm: 5500, factor: 0.6 }, // VTEC crossover
				{ rpm: 5800, factor: 0.9 },
				{ rpm: 8800, factor: 1.0 },
			],
		},
		soundProfile: 'vtec',
		isSpecial: true,
	},
	{
		id: 'vtec_cams',
		name: 'Stage 3 VTEC Cams',
		description: 'Screaming high RPM',
		cost: 2500,
		type: 'ENGINE',
		parentId: 'vtec_engine',
		conflictsWith: [],
		x: 11,
		y: 3,
		stats: {
			redlineRPM: 9500,
			maxTorque: 30,
		},
		isSpecial: true,
	},

	// --- AWD CONVERSION ---
	{
		id: 'awd_conversion',
		name: 'AWD Drivetrain',
		description: 'All-Wheel Drive Swap',
		cost: 8000,
		type: 'TRANSMISSION',
		parentId: null,
		conflictsWith: [],
		x: 10,
		y: 6,
		stats: {
			tireGrip: 2.0, // Massive grip boost
			mass: 100, // Heavy
			finalDriveRatio: 3.8,
		},
		isSpecial: true,
	},
	{
		id: 'active_diff',
		name: 'Active Center Diff',
		description: 'Torque vectoring',
		cost: 4000,
		type: 'TRANSMISSION',
		parentId: 'awd_conversion',
		conflictsWith: [],
		x: 11,
		y: 6,
		stats: {
			tireGrip: 0.5,
		},
		isSpecial: true,
	},
	{
		id: 'sway_bars',
		name: 'Adjustable Sway Bars',
		description: 'Better balance',
		cost: 1000,
		type: 'SUSPENSION',
		parentId: 'coilovers',
		conflictsWith: [],
		x: 6,
		y: 2,
		stats: { tireGrip: 1.25 },
	},
	{
		id: 'chassis_brace',
		name: 'Chassis Bracing',
		description: 'Increased rigidity',
		cost: 1200,
		type: 'SUSPENSION',
		parentId: 'sway_bars',
		conflictsWith: [],
		x: 7,
		y: 2,
		stats: { tireGrip: 1.35 },
	},
	{
		id: 'drag_suspension',
		name: 'Drag Suspension Setup',
		description: 'Optimized for launch',
		cost: 2500,
		type: 'SUSPENSION',
		parentId: 'chassis_brace',
		conflictsWith: [],
		x: 8,
		y: 2,
		stats: { tireGrip: 1.5 },
	},

	// ===== VISUAL CUSTOMIZATION =====
	{
		id: 'paint_red',
		name: 'Red Paint',
		description: 'Classic red',
		cost: 500,
		type: 'PAINT',
		parentId: null,
		conflictsWith: [
			'paint_black',
			'paint_white',
			'paint_gold',
			'paint_purple',
		],
		x: 5,
		y: 4,
		stats: { color: '#ef4444' },
	},
	{
		id: 'paint_black',
		name: 'Black Paint',
		description: 'Murdered out',
		cost: 500,
		type: 'PAINT',
		parentId: null,
		conflictsWith: [
			'paint_red',
			'paint_white',
			'paint_gold',
			'paint_purple',
		],
		x: 5,
		y: 4.7,
		stats: { color: '#111' },
	},
	{
		id: 'paint_white',
		name: 'White Paint',
		description: 'Clean white',
		cost: 500,
		type: 'PAINT',
		parentId: null,
		conflictsWith: [
			'paint_red',
			'paint_black',
			'paint_gold',
			'paint_purple',
		],
		x: 5,
		y: 5.4,
		stats: { color: '#fff' },
	},
	{
		id: 'paint_gold',
		name: 'Gold Paint',
		description: 'Flashy gold',
		cost: 800,
		type: 'PAINT',
		parentId: null,
		conflictsWith: [
			'paint_red',
			'paint_black',
			'paint_white',
			'paint_purple',
		],
		x: 6,
		y: 4,
		stats: { color: '#fbbf24' },
	},
	{
		id: 'paint_purple',
		name: 'Purple Paint',
		description: 'Royal purple',
		cost: 800,
		type: 'PAINT',
		parentId: null,
		conflictsWith: [
			'paint_red',
			'paint_black',
			'paint_white',
			'paint_gold',
		],
		x: 6,
		y: 4.7,
		stats: { color: '#a855f7' },
	},
	{
		id: 'body_kit',
		name: 'Aero Body Kit',
		description: 'Aggressive look',
		cost: 2000,
		type: 'VISUAL',
		parentId: null,
		conflictsWith: [],
		x: 6,
		y: 5.4,
		stats: {},
	},
	{
		id: 'forged_wheels',
		name: 'Forged Wheels',
		description: 'Light + looks',
		cost: 2500,
		type: 'VISUAL',
		parentId: null,
		conflictsWith: [],
		x: 7,
		y: 4.7,
		stats: { mass: 1380 },
	},
];

export const MISSIONS: Mission[] = [
	{
		id: 1,
		name: 'Rookie Night',
		description: 'Race against a local rookie. Easy money.',
		payout: 300,
		difficulty: 'EASY',
		distance: 402, // 1/4 mile
		opponent: {
			name: 'Slow Joe',
			difficulty: 0.2, // Fixed: was speed
			color: '#9ca3af',
			tuning: { ...BASE_TUNING, maxTorque: 160, mass: 1500 },
		},
		xpReward: 100,
	},
	{
		id: 2,
		name: 'Street Tuner',
		description: 'This guy put some money into his hatchback.',
		payout: 800,
		difficulty: 'MEDIUM',
		distance: 402,
		opponent: {
			name: 'Brian',
			difficulty: 0.5,
			color: '#ef4444',
			tuning: {
				...BASE_TUNING,
				maxTorque: 250,
				mass: 1350,
				exhaustOpenness: 0.5,
				turboIntensity: 0.4,
			},
		},
		xpReward: 200,
	},
	{
		id: 3,
		name: 'V8 Thunder',
		description: 'Heavy car, big V8 power.',
		payout: 2000,
		difficulty: 'HARD',
		distance: 804, // 1/2 mile
		opponent: {
			name: 'Dom',
			difficulty: 0.7,
			color: '#111',
			tuning: {
				...BASE_TUNING,
				maxTorque: 500,
				mass: 1600,
				cylinders: 8,
				redlineRPM: 6000,
				exhaustOpenness: 0.8,
				gearRatios: {
					0: 0,
					1: 2.8,
					2: 1.8,
					3: 1.2,
					4: 0.9,
					5: 0.7,
					6: 0.5,
				},
			},
		},
		xpReward: 400,
	},
	{
		id: 4,
		name: 'The 2JZ King',
		description: '1000HP Supra. Good luck.',
		payout: 10000,
		difficulty: 'EXTREME',
		distance: 1000,
		opponent: {
			name: 'Smokey',
			difficulty: 0.95,
			color: '#fbbf24', // Gold
			tuning: {
				...BASE_TUNING,
				maxTorque: 900,
				mass: 1400,
				cylinders: 6,
				redlineRPM: 8500,
				turboIntensity: 1.0,
				exhaustOpenness: 1.0,
				backfireAggression: 1.0,
			},
		},
		xpReward: 800,
	},
	{
		id: 5,
		name: 'Hypercar',
		description: 'Engineering perfection.',
		payout: 50000,
		difficulty: 'IMPOSSIBLE',
		distance: 1609, // 1 Mile
		opponent: {
			name: 'The Baron',
			difficulty: 1.0,
			color: '#fff',
			tuning: {
				...BASE_TUNING,
				maxTorque: 1200,
				mass: 1200,
				cylinders: 12,
				redlineRPM: 9500,
				turboIntensity: 0.5,
				tireGrip: 2.5,
				dragCoefficient: 0.25,
			},
		},
		xpReward: 2000,
	},
	{
		id: 6,
		name: 'BOSS BATTLE: The Baron',
		description: 'Win and take his car.',
		payout: 100000,
		difficulty: 'BOSS',
		distance: 804,
		opponent: {
			name: 'The Baron (Pink Slip)',
			difficulty: 1.0,
			color: '#a855f7',
			tuning: {
				...BASE_TUNING,
				maxTorque: 1400,
				mass: 1100,
				tireGrip: 3.5,
				finalDriveRatio: 3.2,
				turboIntensity: 1.5,
			},
		},
		rewardCar: {
			id: 'boss_car_1',
			name: "Baron's Beast",
			date: Date.now(),
			ownedMods: [
				'ecu1',
				'turbo_kit',
				'big_turbo',
				'intercooler',
				'tires3',
				'drag_slicks',
				'weight3',
				'carbon_panels',
				'sequential',
				'paint_purple',
			],
			disabledMods: [],
			modSettings: {
				big_turbo: { boost_pressure: 3.0 },
			},
			manualTuning: {
				finalDriveRatio: 3.2,
				gearRatios: {
					0: 0,
					1: 3.2,
					2: 2.1,
					3: 1.6,
					4: 1.2,
					5: 1.0,
					6: 0.8,
				},
			},
		},
		xpReward: 5000,
	},
];

export const CONTROLS = {
	GAS: 'ArrowUp',
	SHIFT_UP: 'ArrowRight',
	SHIFT_DOWN: 'ArrowLeft',
	CLUTCH: ' ',
	BRAKE: 'ArrowDown',
	PURGE: 'p',
};

export const RIVALS: Rival[] = [
	{
		id: 'rival_1',
		rank: 5,
		name: 'The Rookie',
		bio: 'Just started racing, but has a fast Civic.',
		difficulty: 0.4,
		color: '#ff0000',

		tuning: { ...BASE_TUNING, finalDriveRatio: 4.1 },
		unlockRequirements: { level: 5 },
		rewards: { money: 5000 },
		status: 'LOCKED',
	},
	{
		id: 'rival_2',
		rank: 4,
		name: 'Street King',
		bio: 'Rules the local streets with an iron fist.',
		difficulty: 0.6,
		color: '#00ff00',

		tuning: { ...BASE_TUNING, finalDriveRatio: 3.9 },
		unlockRequirements: { previousRivalId: 'rival_1' },
		rewards: { money: 10000 },
		status: 'LOCKED',
	},
	{
		id: 'rival_3',
		rank: 3,
		name: 'Drift Queen',
		bio: 'Known for sliding, but can drag race too.',
		difficulty: 0.75,
		color: '#ff00ff',

		tuning: { ...BASE_TUNING, finalDriveRatio: 3.7 },
		unlockRequirements: { previousRivalId: 'rival_2' },
		rewards: { money: 20000 },
		status: 'LOCKED',
	},
	{
		id: 'rival_4',
		rank: 2,
		name: 'Speed Demon',
		bio: 'His car is rumored to be illegal.',
		difficulty: 0.9,
		color: '#ffff00',

		tuning: { ...BASE_TUNING, finalDriveRatio: 3.5 },
		unlockRequirements: { previousRivalId: 'rival_3' },
		rewards: { money: 50000 },
		status: 'LOCKED',
	},
	{
		id: 'rival_5',
		rank: 1,
		name: 'The Boss',
		bio: 'Undefeated. The ultimate challenge.',
		difficulty: 1.2,
		color: '#000000',

		tuning: { ...BASE_TUNING, finalDriveRatio: 3.2 },
		unlockRequirements: { previousRivalId: 'rival_4' },
		rewards: { money: 100000 },
		status: 'LOCKED',
	},
];

export const SKILL_TREE: SkillNode[] = [
	// ====================== ROOT ======================
	{
		id: 'driver_root',
		name: 'Street License',
		description: 'The beginning of your legacy. +2% XP Gain.',
		cost: 0,
		branch: 'DRIVER',
		parentId: null,
		x: 0,
		y: 0,
		stats: { xpGainMultiplier: 1.02 },
	},

	// ====================== DRIVER BRANCH (UP) ======================
	// Tier 1
	{
		id: 'driver_focus1',
		name: 'Focus I',
		description: 'Calm under pressure. +5% Shift Window.',
		cost: 1,
		branch: 'DRIVER',
		parentId: 'driver_root',
		x: 0,
		y: -1,
		stats: { shiftWindowMultiplier: 1.05 },
	},
	// Tier 2 (Left - Adrenaline/XP)
	{
		id: 'driver_adrenaline1',
		name: 'Adrenaline I',
		description: 'Feel the rush. +5% XP Gain.',
		cost: 2,
		branch: 'DRIVER',
		parentId: 'driver_focus1',
		x: -1,
		y: -2,
		stats: { xpGainMultiplier: 1.05 },
	},
	{
		id: 'driver_adrenaline2',
		name: 'Adrenaline II',
		description: 'Addicted to speed. +10% XP Gain.',
		cost: 3,
		branch: 'DRIVER',
		parentId: 'driver_adrenaline1',
		x: -1.5,
		y: -3,
		stats: { xpGainMultiplier: 1.1 },
	},
	// Tier 2 (Center - Precision)
	{
		id: 'driver_focus2',
		name: 'Focus II',
		description: 'Laser focus. +10% Shift Window.',
		cost: 2,
		branch: 'DRIVER',
		parentId: 'driver_focus1',
		x: 0,
		y: -2.5,
		stats: { shiftWindowMultiplier: 1.1 },
	},
	{
		id: 'driver_precision',
		name: 'Precision',
		description: 'Never miss a beat. +15% Shift Window.',
		cost: 4,
		branch: 'DRIVER',
		parentId: 'driver_focus2',
		x: 0,
		y: -3.5,
		stats: { shiftWindowMultiplier: 1.15 },
	},
	// Tier 2 (Right - Reflexes)
	{
		id: 'driver_reflex1',
		name: 'Reflexes I',
		description: 'Quicker launches. -0.005s Reaction Time.',
		cost: 2,
		branch: 'DRIVER',
		parentId: 'driver_focus1',
		x: 1,
		y: -2,
		stats: { reactionTimeBonus: 0.005 },
	},
	{
		id: 'driver_reflex2',
		name: 'Reflexes II',
		description: 'Lightning fast. -0.010s Reaction Time.',
		cost: 3,
		branch: 'DRIVER',
		parentId: 'driver_reflex1',
		x: 1.5,
		y: -3,
		stats: { reactionTimeBonus: 0.01 },
	},
	// Tier 3 (Capstone)
	{
		id: 'driver_legend',
		name: 'Legendary Driver',
		description: 'A living myth. +20% XP, -0.02s Reaction Time.',
		cost: 5,
		branch: 'DRIVER',
		parentId: 'driver_precision',
		x: 0,
		y: -4.5,
		stats: { xpGainMultiplier: 1.2, reactionTimeBonus: 0.02 },
	},

	// ====================== TYCOON BRANCH (RIGHT) ======================
	// Tier 1
	{
		id: 'tycoon_hustle',
		name: 'Hustler',
		description: 'Every race is a payday. +5% Cash.',
		cost: 1,
		branch: 'TYCOON',
		parentId: 'driver_root',
		x: 1,
		y: 0,
		stats: { racePayoutMultiplier: 1.05 },
	},
	// Tier 2 (Up - Sponsors)
	{
		id: 'tycoon_sponsor1',
		name: 'Sponsorship',
		description: 'Brand deals. +10% Cash.',
		cost: 2,
		branch: 'TYCOON',
		parentId: 'tycoon_hustle',
		x: 2,
		y: -1,
		stats: { racePayoutMultiplier: 1.1 },
	},
	{
		id: 'tycoon_sponsor2',
		name: 'Big Sponsor',
		description: 'Major league funding. +15% Cash.',
		cost: 4,
		branch: 'TYCOON',
		parentId: 'tycoon_sponsor1',
		x: 3,
		y: -1.5,
		stats: { racePayoutMultiplier: 1.15 },
	},
	// Tier 2 (Down - Market)
	{
		id: 'tycoon_deal1',
		name: 'Negotiator',
		description: 'Talk them down. -5% Market Fees.',
		cost: 2,
		branch: 'TYCOON',
		parentId: 'tycoon_hustle',
		x: 2,
		y: 1,
		stats: { marketFeeMultiplier: 0.95 },
	},
	{
		id: 'tycoon_deal2',
		name: 'Market Shark',
		description: 'Ruthless trading. -10% Market Fees.',
		cost: 3,
		branch: 'TYCOON',
		parentId: 'tycoon_deal1',
		x: 3,
		y: 1.5,
		stats: { marketFeeMultiplier: 0.9 },
	},
	// Tier 2 (Center - Investor)
	{
		id: 'tycoon_investor',
		name: 'Investor',
		description: 'Smart money. +2% XP from races.',
		cost: 3,
		branch: 'TYCOON',
		parentId: 'tycoon_hustle',
		x: 2.5,
		y: 0,
		stats: { xpGainMultiplier: 1.02 },
	},
	// Tier 3 (Capstone)
	{
		id: 'tycoon_empire',
		name: 'Racing Empire',
		description: 'Own the streets. +20% Cash, -15% Fees.',
		cost: 5,
		branch: 'TYCOON',
		parentId: 'tycoon_investor',
		x: 4,
		y: 0,
		stats: { racePayoutMultiplier: 1.2, marketFeeMultiplier: 0.85 },
	},

	// ====================== MECHANIC BRANCH (LEFT) ======================
	// Tier 1
	{
		id: 'mech_tinkerer',
		name: 'Tinkerer',
		description: 'DIY repairs. -5% Repair Cost.',
		cost: 1,
		branch: 'MECHANIC',
		parentId: 'driver_root',
		x: -1,
		y: 0,
		stats: { repairCostMultiplier: 0.95 },
	},
	// Tier 2 (Up - Salvage)
	{
		id: 'mech_scavenger1',
		name: 'Scavenger',
		description: 'Find good parts. +10% Salvage Yield.',
		cost: 2,
		branch: 'MECHANIC',
		parentId: 'mech_tinkerer',
		x: -2,
		y: -1,
		stats: { salvageYieldMultiplier: 1.1 },
	},
	{
		id: 'mech_scavenger2',
		name: 'Recycler',
		description: 'Nothing wasted. +20% Salvage Yield.',
		cost: 3,
		branch: 'MECHANIC',
		parentId: 'mech_scavenger1',
		x: -3,
		y: -1.5,
		stats: { salvageYieldMultiplier: 1.2 },
	},
	// Tier 2 (Down - Repairs)
	{
		id: 'mech_fixer1',
		name: 'Fixer',
		description: 'Quick patches. -10% Repair Cost.',
		cost: 2,
		branch: 'MECHANIC',
		parentId: 'mech_tinkerer',
		x: -2,
		y: 1,
		stats: { repairCostMultiplier: 0.9 },
	},
	{
		id: 'mech_fixer2',
		name: 'Engineer',
		description: 'Structural reinforcement. -15% Repair Cost.',
		cost: 3,
		branch: 'MECHANIC',
		parentId: 'mech_fixer1',
		x: -3,
		y: 1.5,
		stats: { repairCostMultiplier: 0.85 },
	},
	// Tier 2 (Center - Knowledge)
	{
		id: 'mech_knowledge',
		name: 'Parts Expert',
		description: 'Know your ride. +2% XP.',
		cost: 3,
		branch: 'MECHANIC',
		parentId: 'mech_tinkerer',
		x: -2.5,
		y: 0,
		stats: { xpGainMultiplier: 1.02 },
	},
	// Tier 3 (Capstone)
	{
		id: 'mech_master',
		name: 'Master Mechanic',
		description: 'The machine whispers to you. -25% Repairs, +30% Salvage.',
		cost: 5,
		branch: 'MECHANIC',
		parentId: 'mech_knowledge',
		x: -4,
		y: 0,
		stats: { repairCostMultiplier: 0.75, salvageYieldMultiplier: 1.3 },
	},
];
